[build]
builder = "nixpacks"
buildCommand = "pip install selenium beautifulsoup4 fastapi uvicorn python-dotenv"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/"
healthcheckTimeout = 300

[deploy.env]
PYTHON_VERSION = "3.10"

[phases.setup]
nixPkgs = ["chromium", "chromium-driver"] 