[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y wget gnupg unzip \
    chromium libglib2.0-0 libnss3 libfontconfig1 libgconf-2-4 libxss1 libappindicator3-1 libasound2 && \
pip install --no-cache-dir -r requirements.txt which chromium || which chromium-browser
"""

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 