[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "on-failure" 