[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y wget unzip libglib2.0-0 libnss3 libfontconfig1 libxss1 libappindicator3-1 libasound2t64 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 && \
wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chrome-linux64.zip && \
wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chromedriver-linux64.zip && \
unzip chrome-linux64.zip && mv chrome-linux64 /opt/chrome && \
unzip chromedriver-linux64.zip && mv chromedriver-linux64/chromedriver /usr/bin/chromedriver && \
chmod +x /usr/bin/chromedriver && \
/opt/chrome/chrome --headless=new --no-sandbox --disable-dev-shm-usage --dump-dom https://www.google.com || echo 'CHROME HEADLESS FAILED' && \
pip install --no-cache-dir -r requirements.txt
"""

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 