name = "grt-bus-api"
main = "main.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[build]
command = "pip install -r requirements.txt"

[env.production]
workers_dev = true

[env.production.vars]
ENVIRONMENT = "production"

[site]
bucket = "./" 