name = "grt-bus-api"
main = "main.py"
compatibility_date = "2024-01-01"

[build]
command = "pip install -r requirements.txt"

[env.production]
workers_dev = true
route = "api.yourdomain.com/*"  # Replace with your domain if you have one

[env.production.vars]
ENVIRONMENT = "production" 